version: '3'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/usr/app/
    ports:
      - '5001:5000'
    depends_on:
      - mongodb
    env_file: .env
  mongodb:
    image: mongo:5.0.9
    ports:
      - '27018:27017'
    container_name: mongodb
    volumes:
      - ./mongodata-data:/data/db
